name: Deploy to GitHub Pages

on:
  push:
    branches:
      - blog # 배포할 브랜치 (예: main 또는 master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-lates
    permissions:
      contents: write # GitHub Pages 배포를 위해 쓰기 권한 부여t
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build # out 폴더 생성

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 배포할 브랜치
          folder: out # 배포할 폴더
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
